// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var game, em, phaserDrawableSystem, positionSystem, phaserInputSystem, controllerSystem, out$ = typeof exports != 'undefined' && exports || this;
  out$.game = game = new Phaser.Game(800, 600, Phaser.CANVAS, '', {
    update: update,
    create: create
  });
  out$.em = em = new EntityManager("client");
  function create(){
    phaserDrawableSystem = new PhaserDrawableSystem;
    positionSystem = new PositionSystem;
    phaserInputSystem = new PhaserInputSystem;
    return controllerSystem = new ControllerSystem;
  }
  function update(){
    return em.fixedUpdate(function(){
      phaserInputSystem.loop();
      controllerSystem.loop();
      positionSystem.loop();
      return phaserDrawableSystem.loop();
    });
  }
  em.registerEvent(PLAYER, onPlayerCreate);
  function onPlayerCreate(event){
    console.log('onPlayerCreate');
    return console.log(event.entity);
  }
  net.connect('god', 'localhost', 9000);
  net.onOpen = onOpen;
  function onOpen(id){
    var ref$;
    console.log('onOpen');
    return net.sendEvent((ref$ = new INPUT, ref$.key_up = true, ref$.key_down = true, ref$.key_left = true, ref$.key_right = true, ref$.entity_id = 0, ref$));
  }
}).call(this);
