// Generated by LiveScript 1.2.0
(function(){
  'user strict';
  var out$ = typeof exports != 'undefined' && exports || this;
  function player(){
    var entity, ref$;
    entity = em.createEntity();
    em.addComponent(entity, (ref$ = new CPosition, ref$.x = 5, ref$.y = 5, ref$), SYNC);
    em.addComponent(entity, (ref$ = new CDrawable, ref$.width = 25, ref$.height = 80, ref$.color = 0xF5901D, ref$.type = CDrawable.Type.RECTANGLE, ref$));
    return entity;
  }
  out$.player = player;
}).call(this);
