// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var Net, out$ = typeof exports != 'undefined' && exports || this;
  Net = (function(){
    Net.displayName = 'Net';
    var prototype = Net.prototype, constructor = Net;
    prototype.connections = [];
    function Net(){
      this.onData = this.onDataDefault;
      this.onOpen = this.onOpenDefault;
    }
    prototype.listen = function(peerName, host, port){
      var this$ = this;
      this.peer = new Peer(peerName, {
        host: host,
        port: port,
        debug: 0
      });
      return this.peer.on('connection', function(conn){
        return this$.onConnection(conn);
      });
    };
    prototype.onConnection = function(conn){
      var this$ = this;
      console.log('_onConnection');
      conn.on('open', function(id){
        return this$.onOpen(id);
      });
      conn.on('data', function(data){
        return this$.onData(data);
      });
      return this.connections.push(conn);
    };
    prototype.connect = function(peerName, host, port){
      var this$ = this;
      this.peer = new Peer({
        host: host,
        port: port,
        debug: 0
      });
      this.conn = this.peer.connect(peerName);
      this.conn.on('open', function(id){
        return this$.onOpen(id);
      });
      this.conn.on('data', function(data){
        return this$.onData(data);
      });
      return this.connections.push(this.conn);
    };
    prototype.send = function(data){
      var i$, ref$, len$, conn, results$ = [];
      console.log('send');
      for (i$ = 0, len$ = (ref$ = this.connections).length; i$ < len$; ++i$) {
        conn = ref$[i$];
        console.log('sending' + data);
        results$.push(conn.send(data));
      }
      return results$;
    };
    prototype.onOpenDefault = function(id){
      return console.log('onOpenDefault');
    };
    prototype.onDataDefault = function(data){
      return console.log('onDataDefault');
    };
    return Net;
  }());
  out$.Net = Net;
}).call(this);
