// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  net.listen('god', 'localhost', 9000);
  net.onOpen = onOpen;
  function onOpen(conn){
    console.log('onOpen');
    return net.create(player);
  }
  function dummy(){
    return console.log;
  }
  setInterval(function(){
    return em.fixedUpdate(dummy);
  }, 1000 / 60);
}).call(this);
