// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var player, ref$, bb, x$, position, y$, position2;
  player = em.createEntity();
  em.addComponent(player, (ref$ = new CPosition, ref$.x = 5, ref$.y = 5, ref$));
  em.addComponent(player, (ref$ = new CDrawable, ref$.width = 25, ref$.height = 80, ref$.color = 0xF5901D, ref$.type = CDrawable.Type.RECTANGLE, ref$));
  em.addComponent(player, new CInput);
  em.addComponent(player, new CSpeed);
  bb = new dcodeIO.ByteBuffer();
  bb.writeInt16(42);
  bb.writeInt16(42);
  bb.writeInt16(42);
  net.listen('god', 'localhost', 9000);
  net.onOpen = onOpen;
  x$ = position = new CPosition;
  x$.x = 42;
  x$.y = 42;
  y$ = position2 = new CPosition;
  y$.x = 128;
  y$.y = 128;
  function onOpen(conn){
    console.log('onOpen');
    return net._send(position.toArrayBuffer());
  }
  function dummy(){
    return console.log;
  }
  setInterval(function(){
    return em.fixedUpdate(dummy);
  }, 1000 / 60);
}).call(this);
