// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var System, out$ = typeof exports != 'undefined' && exports || this;
  System = (function(){
    System.displayName = 'System';
    var prototype = System.prototype, constructor = System;
    System.ids = 0;
    prototype.code = 0;
    prototype.entities = {};
    function System(){
      this.id = constructor.ids++;
    }
    prototype.need = function(componentTypeList){
      var i$, len$, componentType;
      for (i$ = 0, len$ = componentTypeList.length; i$ < len$; ++i$) {
        componentType = componentTypeList[i$];
        this.code = this.code | 1 << componentType.id;
      }
      em.registerSystem(this);
      return console.log("system code " + this.code);
    };
    prototype.onEntityAdded = function(entity){
      return console.log("An entity has been added but nothing has been catched");
    };
    prototype.onComponentAdded = function(entity, component){
      return console.log("A component " + component + " added but nothing has been catched");
    };
    return System;
  }());
  out$.System = System;
}).call(this);
