// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var System, out$ = typeof exports != 'undefined' && exports || this;
  System = (function(){
    System.displayName = 'System';
    var prototype = System.prototype, constructor = System;
    System.ids = 0;
    prototype.code = 0;
    prototype.need = function(componentTypeList){
      var i$, len$, componentType;
      this.id = constructor.ids++;
      this.entities = {};
      for (i$ = 0, len$ = componentTypeList.length; i$ < len$; ++i$) {
        componentType = componentTypeList[i$];
        this.code = this.code | 1 << componentType.id;
      }
      return em.registerSystem(this);
    };
    prototype.onEntityAdded = function(entity){
      return console.log("An entity has been added but nothing has been catched");
    };
    prototype.onEntityRemoved = function(entity, component){
      return console.log("An entity has been removed but nothing has been catched");
    };
    prototype.loop = function(){};
    function System(){}
    return System;
  }());
  out$.System = System;
}).call(this);
